language: node_js
node_js:
- "10.0.0"
cache:
  directories:
  - node_modules
before_script:
   - npm install -g firebase-tools
script:
- npm run build
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
before_install:
- openssl aes-256-cbc -K $encrypted_46815668298e_key -iv $encrypted_46815668298e_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
