language: node_js
node_js:
- "10.0.0"
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
before_install:
- openssl aes-256-cbc -K $encrypted_46815668298e_key -iv $encrypted_46815668298e_iv
  -in firebaseConfig.js.enc -out ./src/firebaseConfig.js -d
- openssl aes-256-cbc -K $encrypted_46815668298e_key -iv $encrypted_46815668298e_iv -in setting.js.enc -out src/setting.js -d
